# Site settings
title: Adam Wood
description: The personal site of Adam Wood
url: "https://adamwood.org" # the base hostname & protocol for your site

# User settings
username: Adam Wood
user_description: >- 
  Software Engineer with experience delivering unique solutions in challenging environments. Breadth of knowledge
  covering embedded systems, data processing, visualisation and user interfaces. Experience working directly with 
  technical and non-technical end users in Developer, Technical Lead, Product Owner and Project Management roles.
user_title: Software Engineer
email: contact@adamwood.org
github_username:  wouldadam
cv_location: #

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'gulpfile.js', 'package-lock.json', 'particle.jpg', 'README.md', 'yarn.lock', 'src' , 'node_modules']
