# Site settings
title: Adam Wood
description: The personal site of Adam Wood
url: "https://adamwood.org" # the base hostname & protocol for your site

# User settings
username: Adam Wood
user_description: >- 
  I am a software engineer based in th UK. I have 8+ years of experience delivering high performance data 
  analysis and visualisation software. I have worked in a variety of roles including system architecture, 
  delivery, test and client support. I have experience leading teams and managing individuals.
user_title: Software Engineer
email: contact@adamwood.org
github_username:  wouldadam
cv_location: #

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
